#!/bin/env bash

branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $branch == "main" ]]; then
	other_branch="gh-pages"
else
	other_branch="main"
fi

git switch $other_branch
git merge $branch
git push
git switch main

ssh -t imh << EOF
cd www/ariel
git pull
exit
EOF

