#!/bin/env bash

branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $branch == "main" ]]; then
	other_branch="gh-pages"
else
	other_branch="main"
fi

git switch $other_branch
git merge $branch
git push
if [[ branch == "gh-pages" ]]; then
	git switch $other_branch
fi

ssh -t imh << EOF
cd www/ariel
git pull
exit
EOF

